

const carProduct = [
    {
        type: "search_product",
        name: "Acer Aspire 3 AMD Athlon Silver 3050U Dual-core Processor 15.6(39.6 cms) Laptop - (4 GB / 1TB HDD / Windows 10 Home / AMD Radeon Graphics / 1.9Kg / Silver) A315 - 23",
        image: "https://m.media-amazon.com/images/I/713qk2mtM0L.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 3.5,
        total_reviews: null,
        url: "https://www.amazon.in/Acer-Aspire-Athlon-Dual-core-Processor/dp/B09F9Q17XT/ref=sr_1_1?dchild=1&keywords=laptop&qid=1632816033&sr=8-1",
        availability_quantity: 2,
        spec: {},
        price_string: "₹32,500",
        price_symbol: "₹",
        price: 32500
    },
    {
        type: "search_product",
        name: "Dell Inspiron 3502 15.6 (39.62 cms) HD Display Laptop(Pentium Silver N5030 / 4GB / 256GB SSD / Integrated Graphics / Win 10 + MSO / Accent Black) D560427WIN9BE",
        image: "https://m.media-amazon.com/images/I/51jPUwqQTFL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 4.2,
        total_reviews: null,
        url: "https://www.amazon.in/Dell-Inspiron-Integrated-Graphics-D560427WIN9BE/dp/B08X4N3DW2/ref=sr_1_2?dchild=1&keywords=laptop&qid=1632816033&sr=8-2",
        availability_quantity: null,
        spec: {},
        price_string: "₹40,126",
        price_symbol: "₹",
        price: 40126
    },
    {
        type: "search_product",
        name: "HP Chromebook 14-inch (35.56 cms) Thin & Light Touchscreen Laptop (Celeron N4020/4GB/64GB eMMC + 256GB Expandable Storage/Chrome OS/1.46 kgs Light/ Mineral Silver), 14a-na0003TU",
        image: "https://m.media-amazon.com/images/I/613WULNEr1L.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 3.8,
        total_reviews: null,
        url: "https://www.amazon.in/HP-Chromebook-14a-na0003TU-Touchscreen-Expandable/dp/B08C5W6PL2/ref=sr_1_3?dchild=1&keywords=laptop&qid=1632816033&sr=8-3",
        availability_quantity: null,
        spec: {},
        price_string: "₹27,999",
        price_symbol: "₹",
        price: 27999
    },
    {
        type: "search_product",
        name: "Lenovo Yoga C940 Intel Core i7 10th Gen 14 inch UHD Thin and Light Laptop (16GB/1TB SSD/Windows 10/Office 2019/Mica/1.25Kg), 81Q9009XIN  2020 Apple MacBook Pro (13.3-inch/33.78 cm, Apple M1 chip with 8-core CPU and 8-core GPU, 8GB RAM, 512GB SSD) - Space Grey  Microsoft Surface Pro 7 VDV-00015 12.3 (31.24 cms) Touchscreen 2 -in -1 Laptop(10th Gen Intel Core i5 / 8GB / 128GB SSD / Windows 10 Home / Intel Iris Plus Graphics), Platinum  Acer Swift 5 Intel i5 - 11th Gen 14 inches Full HD IPS Display with Touchscreen Ultra Thin and Light Business Notebook(8GB RAM / 512GB SSD / Windows 10 / Iris Xe Graphics / 1.05 Kg / Mist Green)",
        image: "https://m.media-amazon.com/images/I/71+JZl8vvhL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 4,
        total_reviews: null,
        url: "https://www.amazon.in/Lenovo-Laptop-Windows-Office-81Q9009XIN/dp/B084VXGPR5/ref=sxin_13?asc_contentid=amzn1.osa.eb52e187-919e-4828-910b-83aa2825a3f1.A21TJRUUN4KGV.en_IN&asc_contenttype=article&ascsubtag=amzn1.osa.eb52e187-919e-4828-910b-83aa2825a3f1.A21TJRUUN4KGV.en_IN&creativeASIN=B084VXGPR5&cv_ct_cx=laptop&cv_ct_id=amzn1.osa.eb52e187-919e-4828-910b-83aa2825a3f1.A21TJRUUN4KGV.en_IN&cv_ct_pg=search&cv_ct_we=asin&cv_ct_wn=osp-single-source-pecos-desktop&dchild=1&keywords=laptop&linkCode=oas&pd_rd_i=B084VXGPR5&pd_rd_r=dd281441-4f44-4ea1-9402-23e9e850dd78&pd_rd_w=MAn1q&pd_rd_wg=Xkn02&pf_rd_p=ad2dec93-45d4-46d7-9aa5-3db988563bfc&pf_rd_r=KG000M6AKAX6367F96Y2&qid=1632816033&sr=1-1-c84eb971-91f2-4a4d-acce-811265c24254&tag=technologytoday-21",
        availability_quantity: null,
        spec: {},
        price_string: "₹1,29,900₹1,30,990₹91,038₹69,999",
        price_symbol: "₹",
        price: 129900
    },
    {
        type: "search_product",
        name: "RDP ThinBook 1010 - Intel Celeron Quad Core Processor, 4GB RAM, 64GB Storage, Windows 10 Pro, 14.1” HD Screen",
        image: "https://m.media-amazon.com/images/I/51C6EHkMQpS.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 3.3,
        total_reviews: null,
        url: "https://www.amazon.in/RDP-ThinBook-1010-Celeron-Processor/dp/B0924PSV78/ref=sr_1_4?dchild=1&keywords=laptop&qid=1632816033&sr=8-4",
        availability_quantity: null,
        spec: {},
        price_string: "₹19,990",
        price_symbol: "₹",
        price: 19990
    },
    {
        type: "search_product",
        name: "ASUS VivoBook 14 (2020), 14-inch (35.56 cms) Full HD, AMD Ryzen 3 3250U, Thin and Light Laptop (4GB RAM/1TB HDD/Integrated Graphics/Windows 10/Slate Grey/1.6 kg), M415DA-EB301T",
        image: "https://m.media-amazon.com/images/I/716bvqzz7PL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 3.8,
        total_reviews: null,
        url: "https://www.amazon.in/ASUS-VivoBook-Integrated-Graphics-M415DA-EB301T/dp/B097RKZYGS/ref=sr_1_5?dchild=1&keywords=laptop&qid=1632816033&sr=8-5",
        availability_quantity: null,
        spec: {},
        price_string: "₹31,990",
        price_symbol: "₹",
        price: 31990
    },
    {
        type: "search_product",
        name: "HP 14 (2021) 11th Gen Intel Core i3 Laptop with Alexa Built-in, 8GB RAM, 256GB SSD, 14-Inch (35.6 cm) FHD Screen, Windows 10, MS Office, (14s- dy2501tu)",
        image: "https://m.media-amazon.com/images/I/71bJqS8ZLTL.jpg",
        has_prime: true,
        is_best_seller: true,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 4.2,
        total_reviews: null,
        url: "https://www.amazon.in/HP-Laptop-14-Inch-Windows-dy2501tu/dp/B093VZC5X9/ref=sr_1_6?dchild=1&keywords=laptop&qid=1632816033&sr=8-6",
        availability_quantity: null,
        spec: {},
        price_string: "₹41,890",
        price_symbol: "₹",
        price: 41890
    },
    {
        type: "search_product",
        name: "HP 15 AMD Athlon 15.6 inches HD Laptop, 3050U/4GB/1TB/Windows 10/MS Office (Jet Black/1.85kg), 15s-gy0001au",
        image: "https://m.media-amazon.com/images/I/61bkuSlKF4L.jpg",
        has_prime: false,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 3.5,
        total_reviews: null,
        url: "https://www.amazon.in/HP-Athlon-15-6-inch-Silver-3050U-15s-gy0001au/dp/B08HJYFZ14/ref=sr_1_7?dchild=1&keywords=laptop&qid=1632816033&sr=8-7",
        availability_quantity: null,
        spec: {},
        price_string: null,
        price_symbol: null,
        price: null
    },
    {
        type: "search_product",
        name: "Lenovo IdeaPad Slim 3 AMD Athlon Silver 3050U 15.6 (39.63cm) HD Thin & Light Laptop(4GB / 1TB HDD / Windows 10 / AMD Radeon Graphics / Platinum Grey / 1.85Kg), 81W100W9IN",
        image: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL.jpg",
        has_prime: false,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 3.2,
        total_reviews: null,
        url: "https://www.amazon.in/Lenovo-Integrated-Graphics-Platinum-81W100W9IN/dp/B08JCP96XL/ref=sr_1_8?dchild=1&keywords=laptop&qid=1632816033&sr=8-8",
        availability_quantity: null,
        spec: {},
        price_string: null,
        price_symbol: null,
        price: null
    },
    {
        type: "search_product",
        name: "AVITA Essential Refresh NE14A2INC43A-MB 14-inch/35.56 cm(Intel Celeron-N4020/4GB/128GB SSD/Windows 10 Home/FHD/Integrated Graphics), Matt Black",
        image: "https://m.media-amazon.com/images/I/61YdFkoR9dL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 4,
        total_reviews: null,
        url: "https://www.amazon.in/AVITA-Essential-NE14A2INC43A-MB-Celeron-N4020-Integrated/dp/B08YRNPTM2/ref=sr_1_9?dchild=1&keywords=laptop&qid=1632816033&sr=8-9",
        availability_quantity: 1,
        spec: {},
        price_string: "₹23,490",
        price_symbol: "₹",
        price: 23490
    },
    {
        type: "search_product",
        name: "(Renewed) ASUS VivoBook 14 (2020), Intel Core i3-1005G1 10th Gen, 14-Inch (35.56 cms) FHD Thin and Light Laptop (4GB RAM/1TB HDD/Windows 10/Integrated/Slate Grey/1.6 kg), X415JA-EK104T",
        image: "https://m.media-amazon.com/images/I/51Q0-ezFYyS.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: null,
        total_reviews: null,
        url: "https://www.amazon.in/ASUS-VivoBook-i3-1005G1-Integrated-X415JA-EK104T/dp/B094JW9DGZ/ref=sr_1_10?dchild=1&keywords=laptop&qid=1632816033&sr=8-10",
        availability_quantity: 1,
        spec: {},
        price_string: "₹30,490",
        price_symbol: "₹",
        price: 30490
    },
    {
        type: "search_product",
        name: "Lenovo V15 AMD 15.6-inch (39.6 cm) FHD Thin and Light Laptop (AMD Athlon Silver 3050 U/ 4GB RAM/ 1TB HDD/ Windows 10 Home/Integrated AMD Radeon Graphics/ Iron Grey/ 1.85 kg), 82C700J0IH",
        image: "https://m.media-amazon.com/images/I/71vCx6vbdBL.jpg",
        has_prime: false,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 3.3,
        total_reviews: null,
        url: "https://www.amazon.in/Lenovo-15-6-inch-Integrated-Graphics-82C700J0IH/dp/B095JY5B3F/ref=sr_1_11?dchild=1&keywords=laptop&qid=1632816033&sr=8-11",
        availability_quantity: null,
        spec: {},
        price_string: "₹31,950",
        price_symbol: "₹",
        price: 31950
    },
    {
        type: "search_product",
        name: "Lenovo Ideapad Slim 3 Intel Celeron N4020 15.6 (39.62cm) HD Thin & Light Laptop(4GB / 256 GB SSD / Windows 10 / MS Office / Platinum Grey / 1.7 Kg), 81WQ0099IN",
        image: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: null,
        total_reviews: null,
        url: "https://www.amazon.in/Lenovo-Ideapad-Celeron-Platinum-81WQ0099IN/dp/B09F32YWST/ref=sr_1_12?dchild=1&keywords=laptop&qid=1632816033&sr=8-12",
        availability_quantity: null,
        spec: {},
        price_string: "₹29,990",
        price_symbol: "₹",
        price: 29990
    },
    {
        type: "search_product",
        name: "Lenovo IdeaPad Slim 3 10th Gen Intel Core i3 15.6 (39.63cm) FHD Thin & Light Laptop(8GB / 1TB HDD / Windows 10 / MS Office / Intel UHD Graphics / 2 Year Warranty / Platinum Grey / 1.7Kg), 81WB015GIN",
        image: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 4,
        total_reviews: null,
        url: "https://www.amazon.in/Lenovo-Graphics-Warranty-Platinum-81WB015GIN/dp/B0999BTTKZ/ref=sr_1_13?dchild=1&keywords=laptop&qid=1632816033&sr=8-13",
        availability_quantity: null,
        spec: {},
        price_string: "₹39,990",
        price_symbol: "₹",
        price: 39990
    },
    {
        type: "search_product",
        name: "Lenovo IdeaPad S540 11th Gen Intel Core i7 13.3 QHD IPS Thin & Light Laptop(16GB / 512GB SSD / Windows 10 / MS Office 2019 / Intel Iris Xe Graphics / Iron Grey / 1.28Kg), 82H1002CIN",
        image: "https://m.media-amazon.com/images/I/71QgqHIw7dL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 4.3,
        total_reviews: null,
        url: "https://www.amazon.in/Lenovo-IdeaPad-Windows-Graphics-82H1002CIN/dp/B094XJPQ6N/ref=sr_1_14?dchild=1&keywords=laptop&qid=1632816033&sr=8-14",
        availability_quantity: null,
        spec: {},
        price_string: "₹77,990",
        price_symbol: "₹",
        price: 77990
    },
    {
        type: "search_product",
        name: "Mi Notebook Pro QHD+ IPS Anti Glare Display Intel Core i5-11300H 11th Gen 14-inch(35.56 cms) Thin and Light Laptop (8GB/512GB SSD/Iris Xe Graphics/Win 10/Backlit KB/Fingerprint Sensor/1.4 Kg)",
        image: "https://m.media-amazon.com/images/I/71iiXU7HHkL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 4.2,
        total_reviews: null,
        url: "https://www.amazon.in/Notebook-Display-i5-11300H-Graphics-Fingerprint/dp/B098XM2SJ4/ref=sr_1_15?dchild=1&keywords=laptop&qid=1632816033&sr=8-15",
        availability_quantity: null,
        spec: {},
        price_string: "₹56,999",
        price_symbol: "₹",
        price: 56999
    },
    {
        type: "search_product",
        name: "HP Pavilion 14 11th Gen Intel Core i5 14-inch (35.5 cms) Thin & Light FHD Laptop (8GB/512GB SSD/Windows 10/MS Office/Natural Silver/1.41 kg), 14-dv0543TU",
        image: "https://m.media-amazon.com/images/I/61vQNqvHpTL.jpg",
        has_prime: true,
        is_best_seller: false,
        is_amazon_choice: false,
        is_limited_deal: false,
        stars: 4.4,
        total_reviews: null,
        url: "https://www.amazon.in/HP-Pavilion-14-inch-Windows-14-dv0543TU/dp/B09DGC6C67/ref=sr_1_16?dchild=1&keywords=laptop&qid=1632816033&sr=8-16",
        availability_quantity: null,
        spec: {},
        price_string: "₹62,990",
        price_symbol: "₹",
        price: 62990
    }
]

export default carProduct;